[2024-04-29T20:03:30.048+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T20:03:30.078+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_v14.train scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T20:03:30.089+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_v14.train scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T20:03:30.091+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T20:03:30.113+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train> on 2024-04-28 00:00:00+00:00
[2024-04-29T20:03:30.132+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'predict_v14', 'train', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_predict.py', '--cfg-path', '/tmp/tmpr1evkw6r']
[2024-04-29T20:03:30.145+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask train
[2024-04-29T20:03:30.145+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2118) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T20:03:30.148+0000] {standard_task_runner.py:63} INFO - Started process 2135 to run task
[2024-04-29T20:03:30.350+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_v14.train scheduled__2024-04-28T00:00:00+00:00 [running]> on host d4bc696c9a4e
[2024-04-29T20:03:30.520+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='predict_v14' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T20:03:30.522+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T20:03:30.576+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_predict.py:22 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T20:03:48.453+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T20:03:48.454+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T20:03:48.462+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=predict_v14, task_id=train, execution_date=20240428T000000, start_date=20240429T200330, end_date=20240429T200348
[2024-04-29T20:03:48.525+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T20:03:48.552+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T20:03:48.558+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
